In [29]:
import numpy as np

r = np.random.permutation(50)
r = np.split(r,10)

r2 = np.random.permutation(50)
r2 = np.split(r2,10)

r2

[array([32, 21, 16, 36, 28]),
 array([ 8, 37,  0, 23, 12]),
 array([33, 38, 24, 40, 10]),
 array([44, 34, 29, 47, 45]),
 array([27,  6, 20, 26, 42]),
 array([11,  1, 25, 14, 15]),
 array([30, 49, 19,  4, 22]),
 array([43,  9,  7, 39, 35]),
 array([41,  5, 31, 18,  2]),
 array([13, 46, 17, 48,  3])]

In [17]:
import xlwt 
from xlwt import Workbook 
import xlrd

data = xlrd.open_workbook('AMT_pilot.xlsx')
Md = data.sheet_by_index(0)
Fd = data.sheet_by_index(1)

In [30]:

wb = Workbook()

s1 = wb.add_sheet('Split 1')
s2 = wb.add_sheet('Split 2')
s3 = wb.add_sheet('Split 3')
s4 = wb.add_sheet('Split 4')
s5 = wb.add_sheet('Split 5')
s6 = wb.add_sheet('Split 6')
s7 = wb.add_sheet('Split 7')
s8 = wb.add_sheet('Split 8')
s9 = wb.add_sheet('Split 9')
s10 = wb.add_sheet('Split 10')

S = [s1, s2, s3, s4, s5, s6, s7, s8, s9, s10]

for s in range(0,10):
    for i in range(0, 5):
        row = Md.row(r[s][i])
    #     print(row[0])
        for y in range(0,3):
#             print(row[y])
            S[s].write(i, y, row[y].value)

for s in range(0,10):
    for i in range(0, 5):
        row = Fd.row(r2[s][i])
        for y in range(0,3):
            S[s].write(i+5, y, row[y].value)

In [32]:
# import openpyxl
# workbook=openpyxl.load_workbook('AMT_split.xls')
    
wb.save("AMT_split.xls")